name: Linux Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build project
      run: ./build_proj.sh
    - name: Setup Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - name: install gperf flex bison 
      run: /usr/bin/sudo apt-get install gperf flex bison
    - name: generate javascript binding
      run: python ./tools/generated_javascriptcore_files.py ./source/webkit-2.2.8/Source/JavaScriptCore ./source/webkit-2.2.8/Source/JavaScriptCore/Generated/
    - name: generate webcore binding
      run: python ./tools/generated_webcore_files.py  ./source/webkit-2.2.8/Source/WebCore ./source/webkit-2.2.8/Source/WebCore/Generated/
    - name: build release
      run: make -C ./proj/ BUILDTYPE=Release -j32
