name: Linux Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build project
      run: ./build_proj.sh
    - name: Setup Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - name: generate javascript binding
      run: python ./tools/generated_javascriptcore_files.py
    - name: generate webcore binding
      run: python ./tools/generated_webcore_files.py
    - shell: bash
      run: cd ./proj
    - name: build debug
      run: make
    - name: build release
      run: make BUILDTYPE=Release
