name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
       
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@2008f912f56e61277eefaac6d1888b750582aa16
    
    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7

    - name: Generate Project
      run: ./build_proj.bat
  
    - name: generate javascript binding
      run: python ./tools/generated_javascriptcore_files.py ./source/webkit-2.2.8/Source/JavaScriptCore ./source/webkit-2.2.8/Source/JavaScriptCore/Generated
   
    - name: generate webcore binding
      run: python ./tools/generated_webcore_files.py ./source/webkit-2.2.8/Source/WebCore Generated
    
    - name: Restore Project
      run: msbuild ./vcproj/all.sln /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
     
    - name: Build Solution
      run: msbuild ./vcproj/all.sln /p:Configuration=$env:Configuration -m
      env:
        Configuration: ${{ matrix.configuration }}   

